### PR TITLE
[RFC] New errors package

### PR DESCRIPTION
**Pull request by htdvisser**
This is a request-for-comments pull request. The idea is to pull the `errors` package out of the TTN repo and put it here, so that it's easier to share between projects

### CODE REVIEW

**Comment by johanstokking** [comment]
I'm in favour of promoting this package to utils for sharing. However although the package name and tree seems generic there's dependency on gRPC codes. I don't know if that package should be leading in error codes and stuff for general error handling.

**Comment by htdvisser** [comment]
The idea is that these errors can be communicated between our different components. As this is done with gRPC, I believe that they should integrate with gRPC errors and codes as much as reasonable.

**Comment by johanstokking** [comment]
Then I vote for `github.com/TheThingsNetwork/go-utils/grpc/errors`

**Comment by romeovs** [comment]
@htdvisser I agree that we should use the transport's native error codes where possible, but this package is strongly bound to `grpc`. There's no way to reuse it for HTTP errors for example because the error codes there are different.

On top of that, these grpc codes are not fine-grained enough for internationalization/error message generalization, they lose a lot of information as they are more a kind of error category than an explicit error.

Ideally there would be a custom `Code` type that uniquely encodes the error and maybe even it's internationalized message and on top of that the respective protocol-specific error codes for `grpc`, `http`, etc.

So we'd have a custom error code `19 — Application not registered to handler {handler-id}` and that would turn into our a `grpc` error code `5 — Not Found` and a http `404 — Not Found`.

**Comment by rvolosatovs** [comment]
Why do we need to use the `grpc` codes at all for `erorrs` package? Why not just use types directly? (f.e. `AlreadyExistsError` etc.)
All the needed information could then be obtained by using a type assertion.
We could then have a `grpc/errors` package, which would contain everything `grpc` related.

**Pull request closed without merging**
